version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build process..."
      - echo "Listing directory contents:"
      - ls -R  # List all files and directories recursively to help with debugging
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install  # Install the necessary npm packages
  build:
    commands:
      - echo "Building the frontend project..."
      - npm run build  # Build the frontend project

artifacts:
  files:
    - '**/*'  # Include all files in the artifacts
  base-directory: build  # Change this to the correct output directory if needed

cache:
  paths:
    - node_modules/**  # Cache node_modules to speed up subsequent builds
